import React, { Component } from 'react';
import './sitemap.css';

class Sitemap extends Component {
    render() {
        return (
            
            <div>
    
    <head>
<title>Site Map  Page 1 - Generated by www.xml-sitemaps.com</title>
<meta httpEquiv="Content-type" content="text/html; charset=utf-8" />
</head>
<body>
<div id="cont">
<h1>HTML Site Map</h1>
<h3><a href="https://website-6de1e.firebaseapp.com">Homepage</a>
Last updated: 2017, September 30
</h3>


<table cellPadding="0" cellSpacing="0" border="0" width="100%">

<tr valign="top">
<td className="lpart" colSpan="100"><div className="lhead">/
<span className="lcount">1 pages</span></div>

<table cellPadding="0" cellSpacing="0" border="0" width="100%">

<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/" title="My awesome creation">My awesome creation</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td className="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td className="lpart" colSpan="99"><div className="lhead">admin/
<span className="lcount">2 pages</span></div>

<table cellPadding="0" cellSpacing="0" border="0" width="100%">

<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/admin/upload" title="My awesome creation">My awesome creation</a></td></tr>
<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/admin/delete" title="My awesome creation">My awesome creation</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td className="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td className="lpart" colSpan="99"><div className="lhead">galleries/
<span className="lcount">3 pages</span></div>

<table cellPadding="0" cellSpacing="0" border="0" width="100%">

<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/galleries/eggs" title="My awesome creation">My awesome creation</a></td></tr>
<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/galleries/jewellry" title="My awesome creation">My awesome creation</a></td></tr>
<tr><td className="lpage"><a href="https://website-6de1e.firebaseapp.com/galleries/embrodery" title="My awesome creation">My awesome creation</a></td></tr>
</table>
</td>
</tr>

</table>

<div id="footer">
Page generated by XML-Sitemaps.com - <a target="_blank" rel="noopener noreferrer" href="https://www.xml-sitemaps.com">Google XML sitemap and html sitemaps generator</a>
|
Copyright &copy; 2005-2015

</div>
</div>
</body>
</div>
);

}
}

export default Sitemap;